#!/bin/bash

set -euo pipefail

container_arti="rust:trixie"
container_lyrebird="golang:trixie"
container_arc="debian:trixie"

arti_ver="2.6.0"
lyrebird_ver="0.8.1"

arti_url="https://gitlab.torproject.org/tpo/core/arti/-/archive/arti-v${arti_ver}/arti-arti-v${arti_ver}.tar.gz"
lyrebird_url="https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird/-/archive/lyrebird-${lyrebird_ver}/lyrebird-lyrebird-${lyrebird_ver}.tar.gz"

run_build() {
    set -euo pipefail

    image="${1}"; shift
    func_name="${1}"; shift
    target_os="${1}"

    docker run \
           --rm \
           --env arti_ver="${arti_ver}" \
           --env arti_url="${arti_url}" \
           --env lyrebird_ver="${lyrebird_ver}" \
           --env lyrebird_url="${lyrebird_url}" \
           -v "$(pwd)":/out:Z \
           -w /build \
           "${image}" \
           /bin/bash -c "$(declare -f "${func_name}") && ${func_name} ${target_os}"
}

build_arti() {
    set -euo pipefail

    target_os="${1}"

    case "${target_os}" in
        "linux")
            dependencies="musl-dev"
            cargo_target="x86_64-unknown-linux-musl"
            binary_name="arti"
            ;;

        "windows")
            dependencies="mingw-w64"
            cargo_target="x86_64-pc-windows-gnu"
            binary_name="arti.exe"
            ;;
    esac

    apt-get update -y
    apt-get install -y "${dependencies}"
    rustup target add "${cargo_target}"

    curl -fLO "${arti_url}"
    tar xvf "arti-arti-v${arti_ver}.tar.gz"
    cd "arti-arti-v${arti_ver}"

    cargo build -p arti --locked --release --features static --target "${cargo_target}"
    strip -sv "target/${cargo_target}/release/${binary_name}"

    cp -vf "target/${cargo_target}/release/${binary_name}" "/out/build/${target_os}"
    cp -vf crates/arti/src/arti-example-config.toml "/out/build/${target_os}"
}

build_lyrebird() {
    set -euo pipefail

    target_os="${1}"

    case "${target_os}" in
        "linux") binary_name="lyrebird" ;;
        "windows") binary_name="lyrebird.exe" ;;
    esac

    curl -fLO "${lyrebird_url}"
    tar xvf "lyrebird-lyrebird-${lyrebird_ver}.tar.gz"
    cd "lyrebird-lyrebird-${lyrebird_ver}"

    GOOS="${target_os}" GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-X main.lyrebirdVersion=${lyrebird_ver} -w -s" -v -o "${binary_name}" ./cmd/lyrebird

    cp -vf "${binary_name}" "/out/build/${target_os}"
}

build_arc() {
    set -euo pipefail

    target_os="${1}"

    case "${target_os}" in
        "linux") cp -vf "/out/resources/include/start-arti" "/out/build/${target_os}" ;;
        "windows") cp -vf "/out/resources/include/start-arti.bat" "/out/build/${target_os}" ;;
    esac

    cp -vf "/out/resources/include/arti-${target_os}.toml" "/out/build/${target_os}/arti.toml"
    cp -vrf "/out/build/${target_os}" arti

    case "${target_os}" in
        "linux")
            tar czvf "arti-${arti_ver}-${target_os}-x86_64.tar.gz" arti --owner 0 --group 0 --numeric-owner
            cp -vf "arti-${arti_ver}-${target_os}-x86_64.tar.gz" /out/build
            ;;

        "windows")
            apt-get update -y
            apt-get install -y zip

            zip -Xr "arti-${arti_ver}-${target_os}-x86_64.zip" arti
            cp -vf "arti-${arti_ver}-${target_os}-x86_64.zip" /out/build
            ;;
    esac
}

print_help() {
    printf "Usage: %s <linux | windows>\n" "${0##*/}"
}

if [[ "${#}" -gt 1 ]]; then
    printf "Only 1 argument is accepted\n" 1>&2
    print_help
    exit 1
elif [[ "${#}" -eq 0 ]]; then
    print_help
    exit 0
fi

target_os="${1}"

case "${target_os}" in
    "linux" | "windows") ;;
    *)
        printf "Invalid argument: %s\n" "${target_os}" 1>&2
        print_help
        exit 1
        ;;
esac

mkdir -vp "build/${target_os}"

run_build "${container_arti}" build_arti "${target_os}"
run_build "${container_lyrebird}" build_lyrebird "${target_os}"
run_build "${container_arc}" build_arc "${target_os}"
