#!/bin/bash

set -euo pipefail

container_arti="rust:trixie"
container_lyrebird="golang:trixie"
container_arc="debian:trixie"

arti_ver="1.8.0"
lyrebird_ver="0.7.0"

arti_url="https://gitlab.torproject.org/tpo/core/arti/-/archive/arti-v${arti_ver}/arti-arti-v${arti_ver}.tar.gz"
lyrebird_url="https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird/-/archive/lyrebird-${lyrebird_ver}/lyrebird-lyrebird-${lyrebird_ver}.tar.gz"

build_linux_arti() {
    set -euo pipefail

    curl -LO "${arti_url}"
    tar xvf "arti-arti-v${arti_ver}.tar.gz"
    cd "arti-arti-v${arti_ver}"

    cargo build -p arti --locked --release
    strip -sv target/release/arti

    cp -v target/release/arti /out/release/linux
    cp -v crates/arti/src/arti-example-config.toml /out/release/linux
}

build_linux_lyrebird() {
    set -euo pipefail

    curl -LO "${lyrebird_url}"
    tar xvf "lyrebird-lyrebird-${lyrebird_ver}.tar.gz"
    cd "lyrebird-lyrebird-${lyrebird_ver}"

    CGO_ENABLED=1 go build -ldflags="-X main.lyrebirdVersion=${lyrebird_ver} -w -s" -v -o lyrebird ./cmd/lyrebird

    cp -v lyrebird /out/release/linux
}

build_windows_arti() {
    set -euo pipefail

    apt-get update -y
    apt-get install -y mingw-w64
    rustup target add x86_64-pc-windows-gnu

    curl -LO "${arti_url}"
    tar xvf "arti-arti-v${arti_ver}.tar.gz"
    cd "arti-arti-v${arti_ver}"

    cargo build -p arti --locked --release --target x86_64-pc-windows-gnu --features static
    strip -sv target/x86_64-pc-windows-gnu/release/arti.exe

    cp -v target/x86_64-pc-windows-gnu/release/arti.exe /out/release/windows
    cp -v crates/arti/src/arti-example-config.toml /out/release/windows
}

build_windows_lyrebird() {
    set -euo pipefail

    curl -LO "${lyrebird_url}"
    tar xvf "lyrebird-lyrebird-${lyrebird_ver}.tar.gz"
    cd "lyrebird-lyrebird-${lyrebird_ver}"

    GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-X main.lyrebirdVersion=${lyrebird_ver} -w -s" -v -o lyrebird.exe ./cmd/lyrebird

    cp -v lyrebird.exe /out/release/windows
}

build_linux_arc() {
    set -euo pipefail

    cp -vf /out/resources/include/arti-linux.toml /out/release/linux/arti.toml
    cp -vf /out/resources/include/start-arti /out/release/linux
    cp -vrf /out/release/linux arti

    tar czvf arti-linux.tar.gz arti --owner 0 --group 0 --numeric-owner
    cp -vf arti-linux.tar.gz /out/release
}

build_windows_arc() {
    set -euo pipefail

    apt-get update -y
    apt-get install -y zip

    cp -vf /out/resources/include/arti-windows.toml /out/release/windows/arti.toml
    cp -vf /out/resources/include/start-arti.bat /out/release/windows
    cp -vrf /out/release/windows arti

    zip -Xr arti-windows.zip arti
    cp -vf arti-windows.zip /out/release
}

print_help() {
    printf "Usage: %s <linux | windows>\n" "${0##*/}"
}

if [[ "${#}" -gt 1 ]]; then
    printf "Only 1 argument is accepted\n" 1>&2
    print_help
    exit 1
elif [[ "${#}" -eq 0 ]]; then
    print_help
    exit 0
fi

case "${1}" in
    "linux")
        mkdir -vp release/linux

        docker run --rm \
               --env arti_ver="${arti_ver}" \
               --env arti_url="${arti_url}" \
               --network=host \
               -v "$(pwd)":/out:Z \
               -w /build \
               "${container_arti}" \
               /bin/bash -c "$(declare -f build_linux_arti) && build_linux_arti"

        docker run --rm \
               --env lyrebird_ver="${lyrebird_ver}" \
               --env lyrebird_url="${lyrebird_url}" \
               --network=host \
               -v "$(pwd)":/out:Z \
               -w /build \
               "${container_lyrebird}" \
               /bin/bash -c "$(declare -f build_linux_lyrebird) && build_linux_lyrebird"

        docker run --rm \
               -v "$(pwd)":/out:Z \
               -w /build \
               "${container_arc}" \
               /bin/bash -c "$(declare -f build_linux_arc) && build_linux_arc"
        ;;

    "windows")
        mkdir -vp release/windows

        docker run --rm \
               --env arti_ver="${arti_ver}" \
               --env arti_url="${arti_url}" \
               --network=host \
               -v "$(pwd)":/out:Z \
               -w /build \
               "${container_arti}" \
               /bin/bash -c "$(declare -f build_windows_arti) && build_windows_arti"

        docker run --rm \
               --env lyrebird_ver="${lyrebird_ver}" \
               --env lyrebird_url="${lyrebird_url}" \
               --network=host \
               -v "$(pwd)":/out:Z \
               -w /build \
               "${container_lyrebird}" \
               /bin/bash -c "$(declare -f build_windows_lyrebird) && build_windows_lyrebird"

        docker run --rm \
               -v "$(pwd)":/out:Z \
               -w /build \
               "${container_arc}" \
               /bin/bash -c "$(declare -f build_windows_arc) && build_windows_arc"
        ;;

    *)
        printf "Invalid argument: %s\n" "${1}" 1>&2
        print_help
        exit 1
        ;;
esac
