#!/bin/bash

set -euo pipefail

[[ "$(id -u)" -ne 0 ]] && exec sudo "${0}" "${1:-}"

arti_ver="2.5.0"
lyrebird_ver="0.8.1"

user_name="arti"
bin_dir="/usr/bin"
config_dir="/etc/arti"
doc_dir="/usr/share/doc/arti"
service_dir="/etc/systemd/system"
home_dir="/var/lib/arti"
tmp_dir="/tmp/arti"

pre_install_check() {
    if [[ ! -x "$(command -v systemctl)" ]]; then
        printf "Arti Tor Service depends on systemd\n" 1>&2
        printf "Portable version is available here https://github.com/red-magic/arti-bin/releases\n" 1>&2
        exit 1
    fi

    if id "${user_name}" &> /dev/null; then
        printf "Arti is already installed\n" 1>&2
        exit 1
    fi
}

download_arti() {
    [[ -d "${tmp_dir}" ]] && rm -vrf "${tmp_dir}"

    mkdir -v "${tmp_dir}"
    pushd "${tmp_dir}"

    curl -fLO "https://github.com/red-magic/arti-bin/releases/download/arti-${arti_ver}-lyrebird-${lyrebird_ver}/arti-linux.tar.gz"
    tar xvf arti-linux.tar.gz

    popd
}

install_arti() {
    mkdir -vm 700 "${home_dir}"
    useradd -M -r -s "$(command -v nologin)" -d "${home_dir}" -c "Arti Daemon" "${user_name}"
    chown -v "${user_name}":"${user_name}" "${home_dir}"

    install -vm 755 "${tmp_dir}/arti/arti" -t "${bin_dir}"
    install -vm 755 "${tmp_dir}/arti/lyrebird" -t "${bin_dir}"
    install -vDm 644 resources/arti.toml -t "${config_dir}"
    install -vDm 644 "${tmp_dir}/arti/arti-example-config.toml" -t "${doc_dir}"
    install -vm 644 resources/arti.service -t "${service_dir}"

    rm -vrf "${tmp_dir}"

    printf "\nRun \"systemctl enable arti.service\" to start Arti on boot\n"
    printf "Bridges can be set in %s/arti.toml\n\n" "${config_dir}"
}

pre_remove_check() {
    if ! id "${user_name}" &> /dev/null; then
        printf "Arti isn't installed\n" 1>&2
        exit 1
    elif pgrep -u "${user_name}" &> /dev/null; then
        printf "Arti is still running, stop it first\n" 1>&2
        exit 1
    fi
}

remove_arti() {
    rm -vf "${bin_dir}/arti"
    rm -vf "${bin_dir}/lyrebird"
    rm -vrf "${config_dir}"
    rm -vrf "${doc_dir}"
    rm -vf "${service_dir}/arti.service"

    userdel -r "${user_name}" &> /dev/null
}

case "${1}" in
    "remove")
        pre_remove_check
        remove_arti
        ;;
    "")
        pre_install_check
        download_arti
        install_arti
        ;;
esac
