#!/bin/bash

set -euo pipefail

[[ "$(id -u)" -ne 0 ]] && exec sudo "${0}" "${@}"

arti_ver="1.9.0"
lyrebird_ver="0.8.0"

user_name="arti"
bin_dir="/usr/bin"
config_dir="/etc/arti"
doc_dir="/usr/share/doc/arti"
service_dir="/usr/lib/systemd/system"
home_dir="/var/lib/arti"
tmp_dir="/tmp/arti"

arti_download() {
    if id "${user_name}" &> /dev/null; then
        printf "Arti is already installed\n" 1>&2
        exit 1
    fi

    [[ -d "${tmp_dir}" ]] && rm -vrf "${tmp_dir}"
    mkdir -v "${tmp_dir}"
    pushd "${tmp_dir}"

    curl -fLO "https://github.com/red-magic/arti-bin/releases/download/arti-${arti_ver}-lyrebird-${lyrebird_ver}/arti-linux.tar.gz"
    tar xvf arti-linux.tar.gz

    popd
}

arti_install() {
    mkdir -v "${home_dir}"
    chmod -v 700 "${home_dir}"
    useradd -M -r -s "$(command -v nologin)" -d "${home_dir}" -c "Arti Daemon" "${user_name}"
    chown -v "${user_name}":"${user_name}" "${home_dir}"

    install -vm 755 "${tmp_dir}/arti/arti" -t "${bin_dir}"
    install -vm 755 "${tmp_dir}/arti/lyrebird" -t "${bin_dir}"
    install -vDm 644 "${tmp_dir}/arti/arti-example-config.toml" -t "${doc_dir}"
    install -vDm 644 resources/arti.toml -t "${config_dir}"

    rm -vrf "${tmp_dir}"

    if [[ -x "$(command -v systemctl)" ]]; then
        install -vm 644 resources/arti.service -t "${service_dir}"
        printf "\nRun \"systemctl enable arti.service\" to start Arti on boot\n"
        printf "Bridges can be set in %s/arti.toml\n\n" "${config_dir}"
    fi
}

arti_remove() {
    if ! id "${user_name}" &> /dev/null; then
        printf "Arti isn't installed\n" 1>&2
        exit 1
    elif pgrep -u "${user_name}" &> /dev/null; then
        printf "Arti is still running, stop it first\n" 1>&2
        exit 1
    fi

    rm -vf "${bin_dir}/arti"
    rm -vf "${bin_dir}/lyrebird"
    rm -vrf "${config_dir}"
    rm -vrf "${doc_dir}"

    [[ -x "$(command -v systemctl)" ]] && rm -vf "${service_dir}/arti.service"

    userdel -r "${user_name}" &> /dev/null
}

case "${1:-}" in
    "remove")
        arti_remove
        ;;
    "")
        arti_download
        arti_install
        ;;
esac
