#!/bin/bash

arti_bin="${HOME}/.local/bin/arti"
arti_share="${HOME}/.local/share/arti"
arti_snowflake="${HOME}/.config/arti/snowflake.toml"
arti_log="error"

# Fix connection issues on startup
[[ -d "${arti_share}" ]] && rm -vrf "${arti_share}"

"${arti_bin}" proxy -c "${arti_snowflake}" -l "${arti_log}"
