#!/bin/bash

set -euo pipefail

write_toml() {
    printf "[bridges]\n"
    printf "enabled = true\n"
    printf "bridges = '''\n"
    awk '{print "Bridge " $0}'
    printf "'''\n"
}

./tor-relay-scanner-go -4 -g 100 -s | write_toml > relays.toml
