[bridges]
enabled = true
bridges = '''
Bridge snowflake 192.0.2.3:80 2B280B23E1107BB62ABFC40DDCC8824814F80A72 fingerprint=2B280B23E1107BB62ABFC40DDCC8824814F80A72 url=https://1098762253.rsc.cdn77.org/ fronts=www.cdn77.com,www.phpmyadmin.net ice=stun:stun.antisip.com:3478,stun:stun.epygi.com:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.mixvoip.com:3478,stun:stun.nextcloud.com:3478,stun:stun.bethesda.net:3478,stun:stun.nextcloud.com:443 utls-imitate=hellorandomizedalpn
Bridge snowflake 192.0.2.4:80 8838024498816A039FCBBAB14E6F40A0843051FA fingerprint=8838024498816A039FCBBAB14E6F40A0843051FA url=https://1098762253.rsc.cdn77.org/ fronts=www.cdn77.com,www.phpmyadmin.net ice=stun:stun.antisip.com:3478,stun:stun.epygi.com:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.mixvoip.com:3478,stun:stun.nextcloud.com:3478,stun:stun.bethesda.net:3478,stun:stun.nextcloud.com:443 utls-imitate=hellorandomizedalpn
Bridge obfs4 89.58.28.149:58243 A7C450276E053E887AFAB9518397DE342C30A8E1 cert=9S9H/q/PNhJGmnW96Wm/t3BRZkIrdzTo0Qq/T1ot8+A8JhCwuT1mtJ+PWCvX83aQt100PA iat-mode=0
Bridge obfs4 176.169.236.210:4431 F829D395093B4469808CE7A660AD33AC391FB64A cert=CGZxQnDVoqNLSyERUV5Wf1AklsRCwwSbLbeWjS7Aea6weFwQceg6XnEiXtKEdvWOxm1dMw iat-mode=0
Bridge obfs4 185.177.207.57:13630 A3D55AA6178E80AE486B6DAEAFBA5AB79B29B399 cert=p9L6+25s8bnfkye1ZxFeAE4mAGY7DH4Gaj7dxngIIzP9BtqrHHwZXdjMK0RVIQ34C7aqZw iat-mode=2
Bridge obfs4 191.13.160.98:7774 3D0F7AE757BA1660FF7D615E26FE34603CD745A2 cert=4eEmtsvlBobYH7oMaXL2uPeg1FlpEY7FLFwBGsLpy3B4zVWC5Qz7qHLqtcDOm6xPNUveLg iat-mode=0
'''

[[bridges.transports]]
protocols = ["snowflake"]
path = "~/.local/bin/snowflake-client"
arguments = []
run_on_startup = true

[[bridges.transports]]
protocols = ["obfs4"]
path = "~/.local/bin/obfs4proxy"
arguments = []
run_on_startup = true
