name: Build Arti and Lyrebird

on:
  push:
    tags:
      - 'arti-[0-9]+\.[0-9]+\.[0-9]+-lyrebird-[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  extract-versions:
    runs-on: ubuntu-24.04
    outputs:
      arti_ver: ${{ steps.extract.outputs.arti_ver }}
      lyrebird_ver: ${{ steps.extract.outputs.lyrebird_ver }}

    steps:
      - name: Extract versions
        id: extract
        run: |
          arti_ver=$(echo '${{ github.ref_name }}' | cut -d "-" -f 2)
          lyrebird_ver=$(echo '${{ github.ref_name }}' | cut -d "-" -f 4)
          echo "arti_ver=$arti_ver" >> "$GITHUB_OUTPUT"
          echo "lyrebird_ver=$lyrebird_ver" >> "$GITHUB_OUTPUT"

  build-arti:
    name: arti-${{ matrix.target.os }}
    runs-on: ubuntu-24.04
    container: rust:trixie
    needs: extract-versions
    strategy:
      matrix:
        target:
          - os: linux
            rust-target: '' # Empty because the default target path for Linux is target/release
            binary-name: arti
            cargo-args: ''

          - os: windows
            rust-target: x86_64-pc-windows-gnu
            binary-name: arti.exe
            cargo-args: '--target x86_64-pc-windows-gnu --features static'

    steps:
      - name: Install dependencies (Windows)
        if: matrix.target.os == 'windows'
        run: |
          apt-get update -y
          apt-get install -y mingw-w64
          rustup target add ${{ matrix.target.rust-target }}

      - name: Download and build
        run: |
          mkdir /build
          cd /build
          curl -LO https://gitlab.torproject.org/tpo/core/arti/-/archive/arti-v${{ needs.extract-versions.outputs.arti_ver }}/arti-arti-v${{ needs.extract-versions.outputs.arti_ver }}.tar.gz
          tar xf arti-arti-v${{ needs.extract-versions.outputs.arti_ver }}.tar.gz
          cd arti-arti-v${{ needs.extract-versions.outputs.arti_ver }}
          cargo build -p arti --locked --release ${{ matrix.target.cargo-args }}
          strip -s target/${{ matrix.target.rust-target }}/release/${{ matrix.target.binary-name }}
          mkdir /out
          cp target/${{ matrix.target.rust-target }}/release/${{ matrix.target.binary-name }} /out
          cp crates/arti/src/arti-example-config.toml /out

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: arti-${{ matrix.target.os }}
          path: /out/arti*

  build-lyrebird:
    name: lyrebird-${{ matrix.target.os }}
    runs-on: ubuntu-24.04
    container: golang:trixie
    needs: extract-versions
    strategy:
      matrix:
        target:
          - os: linux
            binary-name: lyrebird
            cgo-enabled: 1

          - os: windows
            binary-name: lyrebird.exe
            cgo-enabled: 0

    steps:
      - name: Download and build
        run: |
          mkdir /build
          cd /build
          curl -LO https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird/-/archive/lyrebird-${{ needs.extract-versions.outputs.lyrebird_ver }}/lyrebird-lyrebird-${{ needs.extract-versions.outputs.lyrebird_ver }}.tar.gz
          tar xf lyrebird-lyrebird-${{ needs.extract-versions.outputs.lyrebird_ver }}.tar.gz
          cd lyrebird-lyrebird-${{ needs.extract-versions.outputs.lyrebird_ver }}
          GOOS=${{ matrix.target.os }} GOARCH=amd64 CGO_ENABLED=${{ matrix.target.cgo-enabled }} go build -ldflags="-X main.lyrebirdVersion=${{ needs.extract-versions.outputs.lyrebird_ver }} -w -s" -v -o ${{ matrix.target.binary-name }} ./cmd/lyrebird
          mkdir /out
          cp ${{ matrix.target.binary-name }} /out

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: lyrebird-${{ matrix.target.os }}
          path: /out/lyrebird*

  release:
    runs-on: ubuntu-24.04
    needs: [extract-versions, build-arti, build-lyrebird]
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Create Linux distribution
        run: |
          mkdir -p linux/arti
          cp artifacts/arti-linux/arti linux/arti
          cp artifacts/arti-linux/arti-example-config.toml linux/arti
          cp artifacts/lyrebird-linux/lyrebird linux/arti
          cp resources/include/arti-linux.toml linux/arti/arti.toml
          cp resources/include/start-arti linux/arti
          chmod 755 linux/arti/arti linux/arti/lyrebird linux/arti/start-arti
          cd linux
          tar czf ../arti-linux.tar.gz arti --owner=0 --group=0 --numeric-owner

      - name: Create Windows distribution
        run: |
          mkdir -p windows/arti
          cp artifacts/arti-windows/arti.exe windows/arti
          cp artifacts/arti-windows/arti-example-config.toml windows/arti
          cp artifacts/lyrebird-windows/lyrebird.exe windows/arti
          cp resources/include/arti-windows.toml windows/arti/arti.toml
          cp resources/include/start-arti.bat windows/arti
          cd windows
          zip -Xr ../arti-windows.zip arti

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          name: Arti ${{ needs.extract-versions.outputs.arti_ver }}
          files: |
            arti-linux.tar.gz
            arti-windows.zip
